name: Build IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: pwa-builder/pwa-action@v1
        with:
          siteUrl: https://thanhson21009-sudo.github.io/olm-app/
          ios: true
      - name: Save App
        uses: actions/upload-artifact@v4
        with:
          name: olm-app-zip
          path: ./*
